# Generated by Django 3.2.10 on 2022-03-02 02:36

from django.db import migrations
from datetime import date
from acola_web import utils


class Migration(migrations.Migration):

    dependencies = [
        ('acola_web', '0001_initial'),
    ]

    def insert_admin(apps, schema_editor):
        UsuarioClass = apps.get_model('acola_web', 'Usuario')
        usuario = UsuarioClass(nome='Administrador',email='adm@acolarapido.br',senha=utils.converter_senha('acola123'),nascimento=date(2000,1,1),admin=True)
        usuario.save()


    operations = [
        migrations.RunPython(insert_admin)
    ]
