# Generated by Django 4.0.3 on 2022-03-04 14:45

from django.db import migrations


'''
Migração para gerar o usuário raiz

E-mail: adm@acolarapido.com
Senha: adm$
'''

class Migration(migrations.Migration):

    dependencies = [
        ('acola_web', '0001_initial'),
    ]

    def inserir_usuario_root(apps, schema_editor):
        usuario_class = apps.get_model('acola_web', 'Usuario')
        usuario = usuario_class()
        usuario.nome = 'Administrador'
        usuario.email = 'adm@acolarapido.com'
        usuario.senha = 'pbkdf2_sha256$320000$HAgcUUSxz4snx8xZIB1Aqn$q2iHVuyfH4RtxRJn15avGPdKY9lrlgVFZ+pDYT+aK4U='
        usuario.admin = True
        usuario.save()

    operations = [
        migrations.RunPython(inserir_usuario_root)
    ]
